package busticket;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Zeynep
 */
public class TicketReservation extends javax.swing.JFrame {

    /**
     * Creates new form Module1
     */
    public TicketReservation() {
        initComponents();
        setExtendedState(Module4.MAXIMIZED_BOTH);
        Color background = new Color(246, 245, 255);
        this.getContentPane().setBackground(background);
        showRouteTable();
        showDeparture();
        showArrival();
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton6.setEnabled(true);
        jRadioButton7.setEnabled(true);
        jRadioButton8.setEnabled(true);
        jRadioButton9.setEnabled(true);
        jRadioButton10.setEnabled(true);
        jRadioButton11.setEnabled(true);
        jRadioButton12.setEnabled(true);
        jRadioButton13.setEnabled(true);
        jRadioButton14.setEnabled(true);
        jRadioButton15.setEnabled(true);
        jRadioButton16.setEnabled(true);
        jRadioButton17.setEnabled(true);
        jRadioButton18.setEnabled(true);
        jRadioButton19.setEnabled(true);
        jRadioButton20.setEnabled(true);
        jRadioButton21.setEnabled(true);
        jRadioButton22.setEnabled(true);
        jRadioButton23.setEnabled(true);
        jRadioButton24.setEnabled(true);
        jRadioButton25.setEnabled(true);
        jRadioButton26.setEnabled(true);
    }

    public void showRouteTable() {
        try {
            Connection con = OracleConnection.getCon();
            String sql = "SELECT * FROM Route";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            DefaultTableModel route = (DefaultTableModel) routeTable.getModel();
            route.setRowCount(0);

            while (rs.next()) {
                Object o[] = {rs.getInt("routeID"), rs.getInt("busID"), rs.getString("departure"), rs.getString("arrival"), rs.getString("routeDate"), rs.getString("routeTime"), rs.getFloat("routeFee")};
                route.addRow(o);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    public void showDeparture() {
        try {
            Connection con = OracleConnection.getCon();
            Statement stat = con.createStatement();
            String query = "SELECT departure FROM Route";
            ResultSet rs = stat.executeQuery(query);

            while (rs.next()) {
                jComboBox1.addItem(rs.getString("departure"));
            }
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void showArrival() {
        try {
            Connection con = OracleConnection.getCon();
            Statement stat = con.createStatement();
            String query = "SELECT arrival FROM Route";
            ResultSet rs = stat.executeQuery(query);

            while (rs.next()) {
                jComboBox2.addItem(rs.getString("arrival"));
            }
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        routeTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        filterRoutes = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        routeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sefer ID", "Otobüs ID", "Kalkış Noktası", "Varış Noktası", "Kalkış Tarihi", "Kalkış Saati", "Sefer Ücreti"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        routeTable.setPreferredSize(new java.awt.Dimension(1240, 600));
        jScrollPane1.setViewportView(routeTable);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(89, 89, 179));
        jLabel2.setText("Kalkış Noktası:");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(89, 89, 179));
        jLabel3.setText("Varış Noktası:");

        filterRoutes.setBackground(new java.awt.Color(89, 89, 179));
        filterRoutes.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        filterRoutes.setForeground(new java.awt.Color(255, 255, 255));
        filterRoutes.setText("Seferleri Filtrele");
        filterRoutes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterRoutesActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(241, 239, 255));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("1");
        jRadioButton1.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2");
        jRadioButton2.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3");
        jRadioButton3.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("4");
        jRadioButton4.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("5");
        jRadioButton5.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("6");
        jRadioButton6.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("7");
        jRadioButton7.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("8");
        jRadioButton8.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("9");
        jRadioButton9.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("10");
        jRadioButton10.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("11");
        jRadioButton11.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText("12");
        jRadioButton12.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setText("13");
        jRadioButton13.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setText("14");
        jRadioButton14.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("15");
        jRadioButton15.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setText("16");
        jRadioButton16.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setText("17");
        jRadioButton17.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setText("18");
        jRadioButton18.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setText("19");
        jRadioButton19.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton20);
        jRadioButton20.setText("20");
        jRadioButton20.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setText("21");
        jRadioButton21.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setText("22");
        jRadioButton22.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton24);
        jRadioButton24.setText("24");
        jRadioButton24.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton25);
        jRadioButton25.setText("25");
        jRadioButton25.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton23);
        jRadioButton23.setText("23");
        jRadioButton23.setMargin(new java.awt.Insets(4, 4, 4, 4));

        buttonGroup1.add(jRadioButton26);
        jRadioButton26.setText("26");
        jRadioButton26.setMargin(new java.awt.Insets(4, 4, 4, 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRadioButton7)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton23)
                        .addGap(65, 65, 65)
                        .addComponent(jRadioButton24)))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jRadioButton21)
                            .addGap(65, 65, 65)
                            .addComponent(jRadioButton22))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jRadioButton25)
                            .addGap(65, 65, 65)
                            .addComponent(jRadioButton26)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton15)
                                    .addComponent(jRadioButton18))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton11)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jRadioButton2))
                                .addGap(57, 57, 57)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton16)
                                    .addComponent(jRadioButton19, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jRadioButton12, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton9)
                                .addComponent(jRadioButton6))
                            .addComponent(jRadioButton3)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton25)
                    .addComponent(jRadioButton23)
                    .addComponent(jRadioButton24)
                    .addComponent(jRadioButton26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton20)
                    .addComponent(jRadioButton21)
                    .addComponent(jRadioButton22))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton17))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton16)
                    .addComponent(jRadioButton15))
                .addGap(20, 20, 20)
                .addComponent(jRadioButton13)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(0, 0, 0))
        );

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(89, 89, 179));
        jLabel4.setText("Ad:");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(89, 89, 179));
        jLabel5.setText("Soyad:");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(89, 89, 179));
        jLabel6.setText("TC No:");

        jButton1.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(89, 89, 179));
        jButton1.setText("ÇIKIŞ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 108, 108));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 28)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Bilet Rezerve Et");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(89, 89, 179));
        jButton4.setText("Uygun Koltukları Görüntüle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book-bus-ticket.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(152, 152, 211));
        jLabel8.setText("Bilet Rezervasyon");

        jPanel2.setBackground(new java.awt.Color(241, 239, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(158, 158, 211), 3, true));

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(158, 158, 211));
        jLabel7.setText("BİLET SORGULAMA");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 19)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(94, 94, 168));
        jLabel9.setText("Lütfen TC numaranızı giriniz:");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(89, 89, 179));
        jButton5.setText("Biletlerimi Sorgula");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, 240, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(filterRoutes, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(255, 255, 255)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(filterRoutes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterRoutesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterRoutesActionPerformed
        try {
            String sql = "SELECT * FROM Route WHERE departure=? and arrival=?";
            Connection con = OracleConnection.getCon();
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, (String) jComboBox1.getSelectedItem());
            pst.setString(2, (String) jComboBox2.getSelectedItem());
            pst.executeUpdate();
            ResultSet rs = pst.executeQuery();
            DefaultTableModel route = (DefaultTableModel) routeTable.getModel();
            route.setRowCount(0);
            while (rs.next()) {
                Object o[] = {rs.getInt("routeID"), rs.getInt("busID"), rs.getString("departure"), rs.getString("arrival"), rs.getString("routeDate"), rs.getString("routeTime"), rs.getFloat("routeFee")};
                route.addRow(o);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_filterRoutesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Connection con = OracleConnection.getCon();
            PreparedStatement pst = con.prepareStatement("insert into ticket(seatNo, routeID, busID, departure, arrival, routeDate, routeTime, routeFee, customerName, customerSurname, customerTC) values(?,?,?,?,?,?,?,?,?,?,?)");
            int seatNo = 0;
            if (jRadioButton1.isSelected()) {
                seatNo = 1;
            } else if (jRadioButton2.isSelected()) {
                seatNo = 2;
            } else if (jRadioButton3.isSelected()) {
                seatNo = 3;
            } else if (jRadioButton4.isSelected()) {
                seatNo = 4;
            } else if (jRadioButton5.isSelected()) {
                seatNo = 5;
            } else if (jRadioButton6.isSelected()) {
                seatNo = 6;
            } else if (jRadioButton7.isSelected()) {
                seatNo = 7;
            } else if (jRadioButton8.isSelected()) {
                seatNo = 8;
            } else if (jRadioButton9.isSelected()) {
                seatNo = 9;
            } else if (jRadioButton10.isSelected()) {
                seatNo = 10;
            } else if (jRadioButton11.isSelected()) {
                seatNo = 11;
            } else if (jRadioButton12.isSelected()) {
                seatNo = 12;
            } else if (jRadioButton13.isSelected()) {
                seatNo = 13;
            } else if (jRadioButton14.isSelected()) {
                seatNo = 14;
            } else if (jRadioButton15.isSelected()) {
                seatNo = 15;
            } else if (jRadioButton16.isSelected()) {
                seatNo = 16;
            } else if (jRadioButton17.isSelected()) {
                seatNo = 17;
            } else if (jRadioButton18.isSelected()) {
                seatNo = 18;
            } else if (jRadioButton19.isSelected()) {
                seatNo = 19;
            } else if (jRadioButton20.isSelected()) {
                seatNo = 20;
            } else if (jRadioButton21.isSelected()) {
                seatNo = 21;
            } else if (jRadioButton22.isSelected()) {
                seatNo = 22;
            } else if (jRadioButton23.isSelected()) {
                seatNo = 23;
            } else if (jRadioButton24.isSelected()) {
                seatNo = 24;
            } else if (jRadioButton25.isSelected()) {
                seatNo = 25;
            } else if (jRadioButton26.isSelected()) {
                seatNo = 26;
            } else {
            }
            pst.setInt(1, seatNo);
            pst.setInt(2, (int) routeTable.getValueAt(routeTable.getSelectedRow(), 0));
            pst.setInt(3, (int) routeTable.getValueAt(routeTable.getSelectedRow(), 1));
            pst.setString(4, routeTable.getValueAt(routeTable.getSelectedRow(), 2).toString());
            pst.setString(5, routeTable.getValueAt(routeTable.getSelectedRow(), 3).toString());
            pst.setString(6, routeTable.getValueAt(routeTable.getSelectedRow(), 4).toString());
            pst.setString(7, routeTable.getValueAt(routeTable.getSelectedRow(), 5).toString());
            pst.setFloat(8, (float) routeTable.getValueAt(routeTable.getSelectedRow(), 6));
            pst.setString(9, jTextField1.getText());
            pst.setString(10, jTextField2.getText());
            pst.setString(11, jTextField3.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Koltuk rezerve edildi!");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        showRouteTable();
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Connection con = OracleConnection.getCon();
            String query = "SELECT COUNT(*) FROM Ticket WHERE customerTC=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, jTextField4.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                int num = rs.getInt(1);
                if (num == 0) {
                    JOptionPane.showMessageDialog(null, "Rezervasyonunuz bulunmamaktadır.");
                } else {
                    JOptionPane.showMessageDialog(null, num + " adet rezervasyonunuz bulunmaktadır.");

                    String sql = "SELECT * FROM Ticket WHERE customerTC=?";
                    pst = con.prepareStatement(sql);
                    pst.setString(1, jTextField4.getText());
                    rs = pst.executeQuery();
                    while (rs.next()) {
                        String message = "Bilet ID: " + rs.getString(1) + "\n"
                                + "Koltuk Numarası: " + rs.getString(2) + "\n"
                                + "Sefer ID: " + rs.getString(3) + "\n"
                                + "Otobüs ID: " + rs.getString(4) + "\n"
                                + "Kalkış Noktası: " + rs.getString(5) + "\n"
                                + "Varış Noktası: " + rs.getString(6) + "\n"
                                + "Kalkış Tarihi " + rs.getString(7) + "\n"
                                + "Kalkış Saati: " + rs.getString(8) + "\n"
                                + "Ücret: " + rs.getString(9) + " TL\n"
                                + "Yolcu Adı: " + rs.getString(10) + "\n"
                                + "Yolcu Soyadı: " + rs.getString(11) + "\n"
                                + "Yolcu TC Numarası: " + rs.getString(12) + "\n";

                        JOptionPane.showMessageDialog(null, message);
                    }
                }
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        jTextField4.setText(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Connection con = OracleConnection.getCon();
            String query = "SELECT seatNo FROM Ticket WHERE routeID=?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, (int) routeTable.getValueAt(routeTable.getSelectedRow(), 0));
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                int seatNo = rs.getInt("seatNo");
                switch (seatNo) {
                    case 1:
                        jRadioButton1.setEnabled(false);
                        break;
                    case 2:
                        jRadioButton2.setEnabled(false);
                        break;
                    case 3:
                        jRadioButton3.setEnabled(false);
                        break;
                    case 4:
                        jRadioButton4.setEnabled(false);
                        break;
                    case 5:
                        jRadioButton5.setEnabled(false);
                        break;
                    case 6:
                        jRadioButton6.setEnabled(false);
                        break;
                    case 7:
                        jRadioButton7.setEnabled(false);
                        break;
                    case 8:
                        jRadioButton8.setEnabled(false);
                        break;
                    case 9:
                        jRadioButton9.setEnabled(false);
                        break;
                    case 10:
                        jRadioButton10.setEnabled(false);
                        break;
                    case 11:
                        jRadioButton11.setEnabled(false);
                        break;
                    case 12:
                        jRadioButton12.setEnabled(false);
                        break;
                    case 13:
                        jRadioButton13.setEnabled(false);
                        break;
                    case 14:
                        jRadioButton14.setEnabled(false);
                        break;
                    case 15:
                        jRadioButton15.setEnabled(false);
                        break;
                    case 16:
                        jRadioButton16.setEnabled(false);
                        break;
                    case 17:
                        jRadioButton17.setEnabled(false);
                        break;
                    case 18:
                        jRadioButton18.setEnabled(false);
                        break;
                    case 19:
                        jRadioButton19.setEnabled(false);
                        break;
                    case 20:
                        jRadioButton20.setEnabled(false);
                        break;
                    case 21:
                        jRadioButton21.setEnabled(false);
                        break;
                    case 22:
                        jRadioButton22.setEnabled(false);
                        break;
                    case 23:
                        jRadioButton23.setEnabled(false);
                        break;
                    case 24:
                        jRadioButton24.setEnabled(false);
                        break;
                    case 25:
                        jRadioButton25.setEnabled(false);
                        break;
                    case 26:
                        jRadioButton26.setEnabled(false);
                        break;
                    default:
                        break;
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Çıkış yapmak istediğinizden emin misiniz?", "UYARI",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            LoginPage obj = new LoginPage();
            obj.setVisible(true);
            dispose();
        } else {
            TicketReservation obj = new TicketReservation();
            obj.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketReservation.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton filterRoutes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable routeTable;
    // End of variables declaration//GEN-END:variables
}
